FROM node:alpine
RUN mkdir -p /tmp
COPY package.json /tmp
RUN cd /tmp && npm install
ENV PATH /tmp/node_modules/.bin:${PATH}

EXPOSE 3000

WORKDIR /app
COPY . .
CMD NOW=$(date +"%y-%m-%d %T") && \
    echo "[$NOW] : client started." >> server.log 2>&1 && \
    rm -rf node_modules && \
    ln -s /tmp/node_modules/ node_modules && \
    npm run dev
