version: '3.3'
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '5050:80'

    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - ./server:/app
        env_file:
            - ./.env

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - ./client:/app
